name: pretrain-med-data-quality                                                                                                                                                                                       
channels:
  - nvidia
  - pytorch   
  - conda-forge                                                                                                                                                                            
  - defaults                                                                                                                                                                                                      
dependencies:                                                                                                                                                                                                     
  - python=3.11   
  - pip   
  - tqdm=4.66.2
  - pytorch=2.2.2                                                                                                                                                                                                       
  - pytorch-cuda=12.1                                                                                                                                                                                          
  - datasets=2.18.0                                                                                                                                                                                                     
  - evaluate=0.4.1                                                                                                                                                                                                      
  - transformers=4.39.3    
  - accelerate=0.29.1   
  - scikit-learn=1.4.1.post1
  - seqeval=1.2.2
  - wandb=0.16.5
  - pip:
    - jsonlines==4.0.0                                                                                                                                                                                    
